[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "bb470d6c3da8fcf58f3c3f46ec761b695c922514"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "db8437b6ccf3c0e9167b0a2dd9d8b7cf4162a2566cec9c8e0e102e5cfbef4634"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+2/xkbcommon.v0.9.1.aarch64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "85c4b9dcd147476f3cc21578473eb94ce08bcf84"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "b2a38f7d72f5d15e4df145a35424759ed9c9f65db01d48c9bcbcc486e7e80897"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+2/xkbcommon.v0.9.1.aarch64-linux-musl.tar.gz"
[[xkbcommon]]
arch = "armv7l"
git-tree-sha1 = "76efb7a368f0c61c337eeec6ca93f42ea9bb30e7"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "eee4b343f62395e9ef353cc1f694ca69338346ef34a855e022836679b0822f51"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+2/xkbcommon.v0.9.1.armv7l-linux-gnueabihf.tar.gz"
[[xkbcommon]]
arch = "armv7l"
git-tree-sha1 = "d730a9cb97d2651d3ea4401b995e61ffe7d3dcd4"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "f858cdf9acac7e4dd9355030971567849b0b7934da8236d4e1856947f9514bd8"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+2/xkbcommon.v0.9.1.armv7l-linux-musleabihf.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "b8286d6b874589ad59c55e1723396f0476661aba"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "36b825d4753c55f62cfcd94a05a2c22a0b05d650c3339274c2e604d23e35c0ab"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+2/xkbcommon.v0.9.1.i686-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "75d3d64c9517f081c23f577da9bdd6487e763892"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "11a2d0948e78f8f9c8c5489f78a38655937acbe89f645263d34c406ee76095f1"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+2/xkbcommon.v0.9.1.i686-linux-musl.tar.gz"
[[xkbcommon]]
arch = "powerpc64le"
git-tree-sha1 = "bb87aaff466616301328e84e14011737b0125054"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "1595b58527b6fce6e0f601599da1f7343c3424ff31a55eb95b4fc46cd4a6662c"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+2/xkbcommon.v0.9.1.powerpc64le-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "503b445a8336624445fceac517b16a6431ae36ec"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "e9121be9e19f9c5722f56e580b72aa352cfce56a37a5795c36f772e3bcb5f304"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+2/xkbcommon.v0.9.1.x86_64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "a17956b62f3602a102fdb60b900b424fa652170e"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "bc0ba3f1606a6a77a907352251e43b8fa2ea4792721ad8e3d6689f2d82a7493a"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+2/xkbcommon.v0.9.1.x86_64-linux-musl.tar.gz"
