[[xkbcommon]]
arch = "armv7l"
git-tree-sha1 = "4cc0bd199495cfe32cd7067c90489d2681526c3c"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "0de4feea59f8c406430045449489c5269c5df812b40e51e03ed27a2abd26aa98"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+1/xkbcommon.v0.9.1.arm-linux-gnueabihf.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "f85bff4497740208f421d10c19fd710d64e41cc3"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "e831fa61a3924253d7499588cc7817c33fa09d15544ccf3c7cbdb94c88b42c1c"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+1/xkbcommon.v0.9.1.i686-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "f1543b8f5428a92f3cb783278c543e78252e2549"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "0c65f2e1f956be31593349674e39590563ec22ded02271bd2ca613e6cd9966d5"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+1/xkbcommon.v0.9.1.i686-linux-musl.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "6cac9acac67bf05ee93fdcdb7f052c05d839c2d7"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "54dcee501ce15ad4811398cf771a78ef4da220d36ab166d5c04cc5b778fe4de3"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+1/xkbcommon.v0.9.1.x86_64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "armv7l"
git-tree-sha1 = "58c18e8b0d0a7207578d331956ec0dfcec9960a9"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "185085350f171d7ad4355f6164a926f8b1b3ec6ab1c8150b72206a4907e5303d"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+1/xkbcommon.v0.9.1.arm-linux-musleabihf.tar.gz"
[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "ce4509371d9ec586cc415291d2ef7189ed804f16"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "0786926fa77aa496e78128afe9a9afaa9f6707afbbc45bd0039770a7f3cc486f"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+1/xkbcommon.v0.9.1.aarch64-linux-musl.tar.gz"
[[xkbcommon]]
arch = "powerpc64le"
git-tree-sha1 = "88b59581f1c07d55c58f7f093809b21b0cb882fa"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "76345037a845a07fe3d96e64ddd89a053a8c3208f4db9508d3b70d158f0ffe11"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+1/xkbcommon.v0.9.1.powerpc64le-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "3b0fa23d30972d3dc49ba4ee7ce7ffa1c1b0d546"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "8a48f8c33c545d0f949ab2e20da431a0414177354f5cc58c7e0680327dece10a"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+1/xkbcommon.v0.9.1.aarch64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "b4aec8294c698d76797e3cfe17fef78c38f2aa85"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "d08759e7302a6f83566cd587373868f008b05bb186bc23d8c8d4639e5ba0b9d4"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+1/xkbcommon.v0.9.1.x86_64-linux-musl.tar.gz"
