[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "79adda47c69d3516d107a46864a21ebb417a445f"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "51f7a4f6b6aa01d51dd56539c7b419867d014e485ed18c90d89e4ef6d42d5924"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+0/xkbcommon.v1.4.1.aarch64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "425d559a60bd4fdf43a77807e3b12aa018238f4e"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "f7d180741bee6f3f16832a266cd2f84210efe99d84932fd683f729bd20c013eb"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+0/xkbcommon.v1.4.1.aarch64-linux-musl.tar.gz"
[[xkbcommon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f7d17ce92a8fa9803d955948c548b146ed8fd13f"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "8fec9aca128716b12d82f51ea092f8a2cdc83052a9329546d28f83ad52074b67"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+0/xkbcommon.v1.4.1.armv7l-linux-gnueabihf.tar.gz"
[[xkbcommon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e88460a190125784e8005d48e6d6a80c3206109d"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "4c30f44a7889be550185d14090a7baed18a431769166528cd4fc33b1c11d8c4a"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+0/xkbcommon.v1.4.1.armv7l-linux-musleabihf.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "508eea1b67fb6b4e9adb9aca7e40f684dc6e4f5f"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "967e26a8939fb8391321216b209060a3e8c3a1e2ddd9287fa61064d7952e357b"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+0/xkbcommon.v1.4.1.i686-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "62f5e4fe310585b754c8b9faa4431a6ebbd8758c"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "10687a97f483eb28c801d318bd37cef7bd7de4521ba28018590af41bff68e50a"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+0/xkbcommon.v1.4.1.i686-linux-musl.tar.gz"
[[xkbcommon]]
arch = "powerpc64le"
git-tree-sha1 = "a2d730f2f58692038f5083041263793516084e85"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "297e8ac2daf36dff0a602cddb5a47ba112eee9c64ade085fcbe1bfa5ae558130"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+0/xkbcommon.v1.4.1.powerpc64le-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "4443e44120d70a97f8094a67268a886256077e69"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "580953526c4e6537e387a75199bc69a397cabe43b69183de791100e2e8d9e95d"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+0/xkbcommon.v1.4.1.x86_64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "99ea9246d21d84e84ce44e90677105fb8cc562fe"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "346285313a5a340486db9215b06ff3f81f9d76d322173422406399d599141049"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+0/xkbcommon.v1.4.1.x86_64-linux-musl.tar.gz"
