[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "cd97d24581d2473642cd65c06a7d2cd4712d9691"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "3ff236a1387a5f9cfe3cb8aa1498efcf4350cbd1ffebdcf0dec268c247f20c74"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.aarch64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "f9729b6e95cfbaa13e36432e7c03b8d430a0d5da"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "d00eaa1828e266b52fd44e1a4cc1a61acd3efee4089944ff19e6beedb612abce"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.aarch64-linux-musl.tar.gz"
[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "d501b23b55927ff4d3c5332b3402b6b27c9e96fc"
os = "freebsd"

    [[xkbcommon.download]]
    sha256 = "34385852c3142b480d1335dfe3010c6a90e54caa86816c6ba251acede0de0aba"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.aarch64-unknown-freebsd.tar.gz"
[[xkbcommon]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fab91f77366e06ce7363aa7f76c17c0bb0daee2f"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "79c9950931c08df911f239431fe2bd921bad0e105e4ddc2ecc4973cdc85ab605"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.armv6l-linux-gnueabihf.tar.gz"
[[xkbcommon]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "def9f038ad06f88021fdad2fbeb39b09b1493eb4"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "4cbf1b6d1fa0bd12aa3ab1a40b3b8c42cc2647cba0d1ba3256bcc34cbe26a029"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.armv6l-linux-musleabihf.tar.gz"
[[xkbcommon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f040aab3c9d7384efb8c06884227d601328f08bd"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "0bb70be26cf9610e235ef46b5561283356be9891ac52174546721b07d65b0e80"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.armv7l-linux-gnueabihf.tar.gz"
[[xkbcommon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7de5c06f42166b6d2f28f43db607e56f7f8f2b59"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "80f26d4abc9d861fb1fe8ecdd8d80ef0f0d494b537b1755bfd109a733106292e"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.armv7l-linux-musleabihf.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "a21c007584324f5ba8a7fabc1bfecdeedbe65410"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "ea735a6b22d7b0e67f56e21c9f3b79a1e80724aa0feb1d755871bc5283fbba29"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.i686-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "0214dafe4679f3f4d995bdb06e88f6668beee7a6"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "137484baffcaca03f42fb2387cdfd429ef1ae0d6fe068ea962bc31767c89a91c"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.i686-linux-musl.tar.gz"
[[xkbcommon]]
arch = "powerpc64le"
git-tree-sha1 = "a762bdc86d3a2d88d59212bd8c6149abdee2d10f"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "c7db7479d90100772622f6502c8f3eb5d73812087e0bb3debc4c678d65cd1e35"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.powerpc64le-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "riscv64"
git-tree-sha1 = "f68497c182d8b1fa9d589e4c003c369e8f599851"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "7e25c30d54ef670c0c580c45b073c6f3dfb2e2b7950b64059cc2fbe1d70741ce"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.riscv64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "ec52107b475256016300d8bda3dc828681b673e6"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "69ccbe52bf1dc92480e34e7725e138d175a3bf751de8cc680cb0c0b5b89232a8"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.x86_64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "92d7caa6ba90a88d0c957d8a751092fc14cc7fb3"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "d17cfad68dbf58bbc4dd94a5a8bb8c71867bdee50dc63fe620a1432305261d31"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.x86_64-linux-musl.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "84f52840bd23981cf045afd53054eb4434e24c8f"
os = "freebsd"

    [[xkbcommon.download]]
    sha256 = "9f4e1662520d78e71f15bf6d30c518dc4046ddf735890b2e726628893011c25f"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.9.2+0/xkbcommon.v1.9.2.x86_64-unknown-freebsd.tar.gz"
