[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "d5f0ee74cbf1284046a4f0b0b3af575ae64160b4"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "1527f94e5b3ba664199e183eddcfaf43ee77df93f469dd19657a219b6c532520"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+2/xkbcommon.v1.4.1.aarch64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "69b570cfc6d022794199e50bda806c61521a6ad5"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "f4d057ba3a4e76f7a91f2f9edc6c28b0c281f093cc1737aef392fa00ec57b327"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+2/xkbcommon.v1.4.1.aarch64-linux-musl.tar.gz"
[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "1c30e46a725e2b96091c14823f387a96de01684a"
os = "freebsd"

    [[xkbcommon.download]]
    sha256 = "f17c675ba24ad210919fe89d413586cbf2a71e648ecf98ef4ed9377a80d2e8e0"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+2/xkbcommon.v1.4.1.aarch64-unknown-freebsd.tar.gz"
[[xkbcommon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7080bd4bcfd673ed651226de2f597f3bf755acb2"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "81fba76e089625349739d07afcab5ba4710b639cdc5113f6c59b3bd6d96a2413"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+2/xkbcommon.v1.4.1.armv7l-linux-gnueabihf.tar.gz"
[[xkbcommon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eac100800e67ba9ca8289da636a888003287ddc0"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "20b2aa65b1cc64ba6fcde8877583e46cc8d2b11b593c682a41c21cd0a4736031"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+2/xkbcommon.v1.4.1.armv7l-linux-musleabihf.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "bb8c30709090e45154936acd659be0ab724483a8"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "fda589d3e70be982deae02db1c7f265a33b26bef168f7faa83884d22c04b4d34"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+2/xkbcommon.v1.4.1.i686-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "3a80fe47d97b2e23836fd0977798b8f6a6b9b369"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "18ce60654600c9b8d9f1a0120369632402da46d34f1e560e7e1533126c9a90d5"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+2/xkbcommon.v1.4.1.i686-linux-musl.tar.gz"
[[xkbcommon]]
arch = "powerpc64le"
git-tree-sha1 = "ff4b50bdd63d34f39afb1a66a06141eee91fb741"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "0a52afc2011048f49075fd4ecfb75715c977e881e52c52c53dafd260a5f47dbf"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+2/xkbcommon.v1.4.1.powerpc64le-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "ab035e8b0b866b38237e59b109fbea663bf2a846"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "08d8e6f6f8adc93db7e1be2234bc728f1fe14c86200357381c9dbabaf83046a8"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+2/xkbcommon.v1.4.1.x86_64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "231098413cada61b9da7934c936e48930cf7365a"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "dbd022aa5edd12772e9b64ea3992f60a4fbbce5779400a56a977ce06649f8099"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+2/xkbcommon.v1.4.1.x86_64-linux-musl.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "2c0316028e37f87e714c95b2f31bf197908e5ab3"
os = "freebsd"

    [[xkbcommon.download]]
    sha256 = "927eefbed069addb2b03da1f8f37014f7dfff661eadddb763434a160332f2319"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+2/xkbcommon.v1.4.1.x86_64-unknown-freebsd.tar.gz"
